### ISSUE TITLE
"Making Smart Connections..." Runs Indefinitely

### ISSUE THREAD

**Issue by LycanDarko666** [brianpetro/obsidian-smart-connections#244] opened 2023-06-14 04:09 UTC
I have two small notes in my Obsidian vault and has been 10 hours and made millions of connections and keeps going. I am unable to use it.

Thought it was hijacking tokens for a second because of it. I was wrong, but unfortunate that I am unable to use it. Sounds like a great idea.

**Comment by brianpetro** [comment] 2023-06-14 11:20
@fenrirlycan are you able to share those notes with me so I can debug this?

Thanks for your help
Brian 🌴

**Comment by ajsteven130** [comment] 2023-06-14 17:15
I am seeing the same thing. Every time a switch to a note note the "Making Smart Connections..." part opens and starts counting up indefinitely. I have well less than 1000 notes in vault. One example I can share is the following:

```markdown
---
type: fleeting_note
tags: status/fleeting_note, status/unprocessed
dates: 2023-06-12 11:31
people: 
relevant: 
aliases: [HCl]
---

# # Hydrochloric Acid








```

**Comment by brianpetro** [comment] 2023-06-14 17:43
@ajsteven130 That counting up doesn't indicate much on it's own.

Check the developer console to see if any errors appear there and if possible screenshot them so I can check them out.


Thanks
🌴

**Comment by ajsteven130** [comment] 2023-06-14 18:01
Once I was able to create the embeddings using the button in the side panel, this stopped happening. Everything seems ok now...

**Comment by ajsteven130** [comment] 2023-06-14 18:01
It only seemed to happen before I had made the embeddings

**Comment by brianpetro** [comment] 2023-06-14 18:04
@ajsteven130 

Glad to hear it's working now.

Thanks for following up!

Brian 🌴

**Comment by fenrirlycan** [comment] 2023-06-15 04:08
It still isn't working for me. I'm a new Obsidian user and I don't have any embeddings. My vault has 13 notes as of today, so definitely not millions of connections to be made, haha. 

> Once I was able to create the embeddings using the button in the side panel, this stopped happening. Everything seems ok now...

I haven't made any embeddings yet, so I guess I'll try that. How do I create the embeddings?

**Comment by fenrirlycan** [comment] 2023-06-15 04:12
Weird, I did nothing different and suddenly it works. I wish I could reproduce the bug so I can give you the debug logs. If it comes up again, I'll try to figure it out a make a PR! Thanks for your hard work, I appreciate it!

**Comment by artworx** [comment] 2023-06-15 06:34
I'm facing the same issue, `Making Smart Connections` has been running for half a day, here is the output from the developer console: 

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/1954578/b9fcce15-433b-4051-8e2d-789ef14eabd3)

The "Manual Save" button creates a file with a single `false` value in in ./.smart-connections/embeddings-3.json

**Comment by brianpetro** [comment] 2023-06-15 11:47
@fenrirlycan 

The embeddings are necessary for the plugin to work. Not sure what you did, but hopefully whatever it was will be fixed soon as I'm cleaning up the codebase. Lots of bugs here and there are simply because this plugin wasn't planned and was more an experiment that continued to gain additional layers. Those layers added up to a lot of unnecessary complexity which I'm (slowly) getting organized into something more manageable.

Thanks for following up
Brian 🌴

**Comment by elarsn** [comment] 2023-06-15 13:03
I had this issue but after stopping and restarting the plugin from settings it now works wonderfull. Really powerful plug-in! Thank you :)

**Comment by tondeaf** [comment] 2023-06-16 00:59
Yes! This happened for all my vaults, just counting up infinitely...

**Comment by brianpetro** [comment] 2023-06-16 01:02
@tondeaf did you check to see if your API key is working in the settings?

Was the plugin working for you prior to this?

Thanks for your help
Brian 🌴

**Comment by tondeaf** [comment] 2023-06-16 01:22
API key works.

Plugin didn't work at all yet. Just started counting Very High. 

Edit: ok, now it looks like something has happened. I guess it shouldn't be counting endlessly? What is the count about? So it vectorizes in the background? May not have access to the vectors yet? 

Ok. This problem is resolved...search works now. But now I will find a different thread for my next issue...

**Comment by brianpetro** [comment] 2023-06-16 13:07
@tondeaf the counting up doesn't mean much. Basically, it was just an indicator I created during the development process to recognize when a process was running. 

Thanks for following up
Brian 🌴

**Comment by AW2307** [comment] 2023-06-17 13:49
First off, this is just such an incredible plugin! @brianpetro 

I also encountered the issue discussed in this thread. What fixed it eventually were these steps:
- Disable and re-enable the plugin in the settings
- Now in the right pane it there were two buttons, one to load an existing embedding file (which could not be found) and one to create embeddings. 
- When I selected the button to create the embeddings, it completed within seconds and now everything is working to my amazement :)

**Comment by brianpetro** [comment] 2023-06-17 13:55
> Now in the right pane there were two buttons, one to load an existing embedding file (which could not be found) and one to create embeddings.

Thanks for clarifying this.

That's a necessary step in the setup process that I need to better document or at least improve the UX.

Thanks,
Brian🌴

**Comment by AW2307** [comment] 2023-06-17 14:08
You're welcome! 
For added clarity: What happened for me was that after first enabling the plugin, it immediately started processing embeddings (and never finished). Then only after disabling and re-enabling the plugin, the buttons were shown.
So if users are supposed to see those buttons from the start, then the behavior upon enabling the plugin would also need to be modified.

**Comment by brianpetro** [comment] 2023-06-17 15:10
@AW2307 yes, that is the intended behavior. It must have been accidentally changed in some past update.

I will have to review that UX to fix it.

Thanks for the clarification and bringing that to my attention 
Brian 🌴

**Comment by MorganOnCode** [comment] 2023-06-19 12:55
Came here to report this bug: 
I've got 2,000+ notes in my vault, and the counter is currently at 500,000 and counting.

Its comforting reading that this is not a token count or related to the API - I thought this was racking up an initiation bill $$

Some guidance would be great here: 
1. I'm not seeing any `.smart-connections` folder in my .obsidian hidden folder.
2. I'm not seeing any .embeddings.json file either

Should I create these manually? 
Should I do a reinstall of the plugin? 

I'm afraid to interrupt the process as it's been more than an hour to get this far, with no buttons appearing. 
Thanks in advance!

**Comment by MorganOnCode** [comment] 2023-06-19 15:55
Thank you so much @brianpetro - I just updated the plugin and it's resolved for me; the two buttons appeared, and I've initiated the embeddings file.

**Comment by Sheemie** [comment] 2023-06-22 21:10
<img width="727" alt="Screenshot 2023-06-22 at 5 09 36 PM" src="https://github.com/brianpetro/obsidian-smart-connections/assets/111518155/9d77d660-a643-469d-8d4b-7897982def6e">

I still can't see any buttons and the plug-in is still running infinitely

**Comment by brianpetro** [comment] 2023-06-22 21:59
@Sheemie did you hit the "create embeddings.json" button?

🌴

**Comment by Sheemie** [comment] 2023-06-22 22:44
Thank you @brianpetro for the reply. My issue is I don’t know where are the buttons. I attached the screenshot which shows two buttons when the plug-in starts making smart connections. None of them relates to embedding. Did I miss something?

By the way, I can’t wait to use your plug-in. I have no doubt that this is going to be fantastic. Thank you for making this.

**Comment by brianpetro** [comment] 2023-06-23 00:04
@Sheemie try turning on an off the plugin without any notes open. The buttons should appear in the same place as your screenshot.

🌴

**Comment by brianpetro** [comment] 2023-06-23 00:07
@Sheemie it should look like this
![Screenshot 2023-06-22 at 8 06 27 PM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/7edff8df-c858-4730-afd8-4a5910b1823b)

**Comment by Sheemie** [comment] 2023-06-23 00:45
Maybe I could delete the file to trigger it?

**Comment by LycanDarko666** [comment] 2023-06-28 02:44
I still can't get this working on my setup. I'm running Obsidian on Linux, maybe that's why. Bummer. Let me know if there is anything I can provide to help you fix this bug.

**Comment by brianpetro** [comment] 2023-06-28 07:30
@LycanDarko666 thanks for letting me know about this. It seems like quite a few people keep having this issue during the initial setup. I will have to continue to look into it further.

Thanks,
Brian

**Comment by annekaelber** [comment] 2023-08-10 02:31
I installed the plugin today and set up the OpenAI API key, including setting up a payment method (and limits!). I can see there, I've spent 7 cents. So, something is working correctly. Or maybe not -- it's been saying ` Making Smart Connections....` for about 15 minutes now, but my OpenAPI use has not changed.

Moving around in my vault has been incredibly sluggish since I first enabled the plugin. That suggests the embedding process  may still be running? Is there's another indicator besides` Making Smart Connections....` to let me know it's still working? Or maybe a general time expection, like "x files | k content = y minutes to process"? If it's the API timing out and needing to wait to continue, is there a log where I can read the progress? (I've seen reference to "the (developer) console". Is this accessible by anyone -- if so how do I open it?) If it's still processing, I should see the numbers on OpenAI's usage dashboard to go up, but they aren't.

I'm on Win 10 Home, running Obsidian 1.4.2 and Smart Connections 1.6.34. LMK if there's other information I can provide. It appears you hear this frequently already, but this looks to be a powerful plugin and I'm eager to see it in action!

Thanks for all the awesomeness,
Anne

**Comment by brianpetro** [comment] 2023-08-10 11:38
@annekaelber see this comment https://github.com/brianpetro/obsidian-smart-connections/issues/289#issuecomment-1673051941

If you haven't already, restarting Obsidian may also help.

If you're still having issues after that, let me know. 

Thanks,
Brian 🌴

**Comment by annekaelber** [comment] 2023-08-10 22:45
> @annekaelber see this comment [#289 (comment)](https://github.com/brianpetro/obsidian-smart-connections/issues/289#issuecomment-1673051941)
> 
> If you haven't already, restarting Obsidian may also help.
> 
> If you're still having issues after that, let me know.
> 
> Thanks, Brian 🌴


It appears to be okay. The only failed file is the output for the Find orphans plugin, which I'm not concerned about. I haven't had a chance to 'test drive' and see if the sluggish-ness is also gone. Will report back one way or the other. Thank you for your replies!

**Closed** 2024-07-02 17:01 UTC
