### ISSUE TITLE
Bug: Continually embedding

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#8] opened 2022-12-28 19:00 UTC
Plugin has been embedding for a long time. Not sure if it's doing something productive or running into an issue. I'm seeing an error 429 frequently:

<img width="245" alt="Screenshot 2022-12-28 at 13 57 45" src="https://user-images.githubusercontent.com/7927356/209859764-e795ae99-ec9f-4e9c-80a4-cd0b7beefbfe.png">

Obsidian is also just generally laggy while this is going on.

**Comment by brianpetro** [comment] 2022-12-28 19:32
The 429 happens when you get rate limited because the code embeds notes on
batches of 10 at a time, and sometimes Open AI returns 429 at that rate.
That should be OK because it should re-embed only those notes the next time
it runs, which happens every time you open a new note or run the "Find
Connections" command.

The embeddings shouldn't re-run unless the `file.mtime` changes, which
happens when you update the note.

Since you have 20K notes, the code could still be catching up to cover all
the rate-limited notes with embeddings. The full process takes much less
than a minute with my 1,500 notes. And besides your very first run of the
embeddings, which may take up to 15 minutes, it should always finish
processing in less than a minute after that.

The reason is, once the embeddings process is complete across all of the
notes, then it should only scan the notes to look for changes in
`file.mtime` and deleted notes to update the embeddings for those.

One thing to be aware of is if you have any other active plugins that may
be updating the `file.mtime` in the background, then that could be
triggering unnecessary additional embeddings. This is unlikely but possible
so I wanted to mention it.

Any additional notes you can provide about the performance, like after
which specific actions it feels most laggy, would be a big help as I turn
my eye to the performance updates.

Thanks!

**Comment by arminta7** [comment] 2022-12-28 22:17
I turned off all other plugins and left it for a bit and it seemed to have completed. But has now started repeating some notes again. Notes that I'm pretty sure aren't being modified. Here are some other errors I found going through the console:

<img width="280" alt="Screenshot 2022-12-28 at 17 12 29" src="https://user-images.githubusercontent.com/7927356/209879286-683b3627-e3a8-4956-80b9-f36ed4bc7d82.png">

<img width="303" alt="Screenshot 2022-12-28 at 17 14 16" src="https://user-images.githubusercontent.com/7927356/209879367-50293390-a728-4970-b3fe-ec789ccdcddb.png">

<img width="306" alt="Screenshot 2022-12-28 at 17 14 54" src="https://user-images.githubusercontent.com/7927356/209879392-1890cc18-0479-4a82-b0b8-821f89e41f13.png">

**Comment by brianpetro** [comment] 2022-12-29 01:37
Thanks for sharing your console logs. 

I improved the logging. The new thing to pay attention to is the `files_embedded` log. Every "run" will display the number of files embedded in the console. This will help us determine how many files are being re-embedded each run. This way we can better diagnose the performance issues from there.

I attached a screenshot of what my console typically looks like after this latest update.

![logs](https://user-images.githubusercontent.com/1886014/209892195-4ff43795-31bb-4eba-93c4-d53907a9496e.png)

**Comment by arminta7** [comment] 2022-12-29 01:45
I don't see that at all.

I have some of these:
<img width="353" alt="Screenshot 2022-12-28 at 20 40 51" src="https://user-images.githubusercontent.com/7927356/209892688-3f7dfc9e-cf9d-4d93-b623-4ba5263256b9.png">
<img width="363" alt="Screenshot 2022-12-28 at 20 41 05" src="https://user-images.githubusercontent.com/7927356/209892695-794bd54c-ed01-4ba3-bb8a-f6072cb67d64.png">
<img width="341" alt="Screenshot 2022-12-28 at 20 42 27" src="https://user-images.githubusercontent.com/7927356/209892705-78232147-b222-4232-8751-881f4cf213fc.png">

It was getting 429 over and over probably 100's of times, wouldn't stop when I turned off the plugin. I had to force reload Obsidian.

**Comment by brianpetro** [comment] 2022-12-29 02:00
I wonder if your `.smart-connections/embeddings.json` is getting cleared somehow. 

The 429 errors may need to be addressed by slowing down bulk embeds. But that error is otherwise harmless.

I also added the `erroneous embed` log to see which notes are triggering non-429 (400) errors. The OpenAI API doesn't like something in that note. It's hard to say, but if you could share that entire note with me, I could try to reproduce it.

**Comment by arminta7** [comment] 2022-12-29 02:03
I got that error (erroneous embed) quite a lot. Here's the content of one of them:

## Sample sleep schedule for a 10-month-old

The exact timing for bedtime and naps varies from baby to baby. But when it comes to [sleep schedules](https://www.whattoexpect.com/first-year/baby-sleep-schedule.aspx), your 10-month-old has probably fallen into a fairly predictable pattern.

Babies this age usually wake on the early side, take a morning and an afternoon nap, and go to bed between 7 p.m. and 8 p.m., getting 10 to 12 hours of sleep during the night. At 11 and 12 months, she will likely follow a similar schedule.

Here’s an example of what your 10-month-old's sleep schedule might look like:

-   7:00 a.m.: Awake
-   9:30 a.m.: Nap
-   11:00 a.m.: Awake
-   2:30 p.m.: Nap
-   4:00 p.m.: Awake
-   7:00 p.m.: Bedtime routine
-   7:30 p.m.: Bedtime

**Comment by arminta7** [comment] 2022-12-29 02:06
Should I maybe try to uninstall, wipe the embeddings file and start over?

**Comment by brianpetro** [comment] 2022-12-29 02:11
Don't wipe the file. Best to never delete it.

**Comment by brianpetro** [comment] 2022-12-29 02:24
Copy & pasting that file worked fine for me.

Are the same files repeatedly ending up in the `erroneous embed input` log? 

If yes, you can try uploading one of the files and I can try to reproduce using that.

If the same files aren't repeatedly appearing, then they may work after a second/third try and eventually stop appearing altogether 🤞.

**Comment by arminta7** [comment] 2022-12-29 03:35
Here's one file I keep seeing. I am getting actual link suggestions in the sidebar now on some pages, but when selecting the note below I got this error. With the new logging it's very difficult to troubleshoot because the note contents are usually quite long and trying to scroll through and see what's happening or what might be repeating is tough. 

<img width="420" alt="Screenshot 2022-12-28 at 22 32 38" src="https://user-images.githubusercontent.com/7927356/209899833-8bbd8396-8c57-4ef9-ab0b-cc6764bfb9c2.png">

[DarkHorse Podcast with Daniel Schmachtenberger & Bret Weinstein.md](https://github.com/brianpetro/obsidian-smart-connections/files/10317444/DarkHorse.Podcast.with.Daniel.Schmachtenberger.Bret.Weinstein.md)

**Comment by arminta7** [comment] 2022-12-29 03:42
As I'm clicking through it seems to be resolving some and I'm seeing more of this like you showed above:

<img width="380" alt="Screenshot 2022-12-28 at 22 37 23" src="https://user-images.githubusercontent.com/7927356/209900159-ad743e44-1e91-45ad-bf35-723611da7efd.png">

I feel like the issue is maybe with whatever related links it's trying to pull up? Because navigating to specific notes always causes an issue and others are fine.

**Comment by brianpetro** [comment] 2022-12-29 03:54
I just pushed an update that cleans up the logs and improves the batching, so you should see fewer 429s. 

It's good to see that "files embedded: 0" because that means it atleast thinks it's up-to-date on the embeddings.

Also, I was able to reproduce the error with that file you uploaded. Still looking into it...

**Comment by brianpetro** [comment] 2022-12-29 04:24
From the note you shared I was able to identify an edge case where long headings and sections were exceeding the 8,000 tokens limit. I placed a restriction to prevent that from happening in the latest update.

**Comment by arminta7** [comment] 2022-12-29 22:17
I'm not sure if this is related, so I'm putting it here: 
1. The retrying request seems to be continually running. 
2. My OpenAI cost has been very high, min $15 per day, for the embeddings. I've had over 85k requests today already. I would expect the initial run to be high, but it hasn't let up.

**Comment by brianpetro** [comment] 2022-12-29 23:09
1. Is it the 429 retrying error? If so, those should stop as soon as all of your files are initially processed. Though I would have expected yours to have been completed by now, maybe it's a different error code. 


2.
Once all your Embeddings are completed, the usage will be reduced to just the new and modified files. That will change depending on your usage, but it's just been pennies per day for me, though I am pretty restrictive with what I keep in my notes. OpenAI advertises something like embedding "3,000 pages for $1" it's hard to imagine making that many note changes, but there are always outliers. And large notes will be less efficient regarding cost.

$30 for an initial run makes sense to me based on your vault size. Open AI billing day ends at midnight at UTC+0 (7 pm EST), so the processing last night was probably split across both days. Have you looked at the hourly usage? I would expect that the bulk of tokens used was last night and split to both days, as opposed to persistent usage throughout today.

Unless large swaths of your files are being updated programmatically (based on `file.mtime` change), that usage amount should be a one-time occurrence.

The only other reason it would re-embed all the files is if the `embeddings.json` file got deleted.

**Comment by brianpetro** [comment] 2022-12-30 12:41
@arminta7 I'm closing this issue in favor of starting new error-specific issues as they arise. Feel free to [schedule a call with me](https://wfhbrian.com/build-with-ai/). It would be great for me to have a chance to chat with a power user like yourself. Thanks for all your help getting the plugin up to speed!

**Closed by brianpetro** 2022-12-30 12:41 UTC
