### ISSUE TITLE
White on White

### ISSUE THREAD

**Issue by quelsemme** [brianpetro/obsidian-smart-connections#412] opened 2024-01-13 05:37 UTC
I use a dark theme, but not sure it's related.

Since updating to v2, the chat box input field is white with black text (instructional text) but when I type into it, it types white on white and I can't see what I'm typing.

**Comment by uther79** [comment] 2024-01-14 08:55
I didn't update to v2 but  only the normal plugin update. 
I have the same issue:

_my typed text in the "CHAT-command field" is white on white and therefore not visible._

I'm using the theme "Obsidian Nord" in dark mode.
When switching to white mode I can see my typing in black on white.

**Comment by brianpetro** [comment] 2024-01-14 15:19
@uther79 @quelsemme 

Thanks for letting me know, I'm going to try to look into this today!

**Comment by brianpetro** [comment] 2024-01-14 18:49
@uther79 I tried with Obsidian Nord and couldn't reproduce this. Can you send me a screenshot so I can see what you're seeing?

@quelsemme Which theme are you using? Similarly, a screenshot would be helpful.

Thanks for your help in solving this!

🌴

**Comment by uther79** [comment] 2024-01-14 19:03
Here are some hardcopies from my obsidian ...

[Smart-Connections Entry white on white.pdf](https://github.com/brianpetro/obsidian-smart-connections/files/13932780/Smart-Connections.Entry.white.on.white.pdf)

**Comment by brianpetro** [comment] 2024-01-14 19:07
@uther79 thanks, that helps. Are you using Windows? I tested Obsidian Nord on mac, but maybe it's an OS-specific isasue.

**Comment by uther79** [comment] 2024-01-14 19:09
Yes 
Win 10 

Let me have a loog at my MacBook Air 
I need some minutes ...

**Comment by brianpetro** [comment] 2024-01-14 19:10
I'm checking out Windows now

**Comment by uther79** [comment] 2024-01-14 19:15
The same behaviour on MacBook Air M1 (8GB, OS version: "Ventura 13.3.1")

**Comment by brianpetro** [comment] 2024-01-14 19:20
Interesting, I just checked windows and it looks the same for me on both, too.

Is it possible that you have another plugin active that is doing something with text inputs?

Besides that, I'm going to have to think about what else might be causing this. Maybe @quelsemme might have an idea when they see this.

![Screenshot 2024-01-14 at 2 16 29 PM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/ca2111f5-9b00-4316-8d93-7b9087a2fdb3)
🌴

**Comment by uther79** [comment] 2024-01-14 19:32
The plugin "Text Generator" is causing this error / strange behaviour!
After disabling it, the chat input field is "back again" and looks normal again (like your screenshot)

**Comment by brianpetro** [comment] 2024-01-14 19:39
@uther79 thanks for solving this!

I wonder why Text Generator is altering `textarea` elements. 

🌴

**Comment by brianpetro** [comment] 2024-01-14 19:46
I created an issue in the Text Generator repo, hopefully it gets taken care of because I imagine this is causing issues elsewhere in addition to Smart Connections.

🌴

**Comment by quelsemme** [comment] 2024-01-15 06:27
I can second that. Disabling Text Generator fixed the issued.
Strange, since that plugin doesn't have a sidebar/window and doesn't do any visual stuff. It's just an OpenAI API callout.

I disabled it for now because I don't use it all that much, and Smart Connections Chat can do what it does anyway via the API.

**Comment by uther79** [comment] 2024-01-15 14:19
The issue was fixed by Text Generator with their new version 0.63

**Comment by brianpetro** [comment] 2024-01-15 14:35
@uther79 great, I'll close this one

**Closed by brianpetro** 2024-01-15 14:35 UTC
