### ISSUE TITLE
BR: frequent response failures (moved from #84 - possible dupe of #51)

### ISSUE THREAD

**Issue by pinuke** [brianpetro/obsidian-smart-connections#88] opened 2023-03-24 21:31 UTC
### Discussed in https://github.com/brianpetro/obsidian-smart-connections/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **isaac3203** March 24, 2023</sup>
<img width="592" alt="image" src="https://user-images.githubusercontent.com/84989111/227466315-369192cc-546d-4a15-a277-b44fee201264.png">

frequent response failures</div>

**Comment by dartungar** [comment] 2023-03-25 14:43
I get the same error. Here are (probably) it's details:
![image](https://user-images.githubusercontent.com/36126057/227724217-9815e91b-e381-4b9f-875e-ab7538c03514.png)

**Comment by smartguy1196** [comment] 2023-03-25 19:07
@dartungar post that in https://github.com/brianpetro/obsidian-smart-connections/issues/51

@brianpetro this issue may be a duplicate of #51. We would need the OP for #84 to confirm

**Closed as completed** 2023-03-30 01:31 UTC
