### ISSUE TITLE
Installing the plugin freezing my computer

### ISSUE THREAD

**Issue by flowingblaze** [brianpetro/obsidian-smart-connections#597] opened 2024-05-11 03:58 UTC
I have 7810 files in my vault and when I install the plugin and it does its "making smart connections" process is slows down by ALOT. It seems/is frozen. The farthest it has gotten in my vault is 5140 files out of 7810. I can only uninstall it by deleting the .obsidian folder

**Comment by christianngarcia** [comment] 2024-05-18 15:43
This is something that has been worked on in the past week. Please make sure you are on the latest version and let us know if it is still an issue 🌸

**Comment by flowingblaze** [comment] 2024-05-18 21:19
still an issue. i have the latest version.

**Comment by brianpetro** [comment] 2024-06-06 12:45
@flowingblaze performance of this process was further addressed in the latest update, `v2.1.69`.

It is also possible that this is being caused by extremely long notes. If you have any notes with >100K words, it may be worth excluding them in the settings. You may also try setting block-level embeddings to "None".

If this is still a problem after updating, please re-open this issue and let me know.

Thanks for your help in solving this
🌴

**Closed by brianpetro** 2024-06-06 12:45 UTC
